//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IncidentModuleWebsite.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Contractor
    {
        public int ContractorId { get; set; }
        public string Company { get; set; }
        public string ReasonForEntry { get; set; }
        public System.DateTime StartDate { get; set; }
        public System.DateTime ExpectedFinishDate { get; set; }
        public Nullable<System.DateTime> FinishedDate { get; set; }
    }
}
