//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IncidentModuleWebsite.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Incident
    {
        public int IncidentId { get; set; }
        public string IncidentType { get; set; }
        public string Severity { get; set; }
        public string Internal { get; set; }
        public string IncidentLocation { get; set; }
        public string PeopleInvolved { get; set; }
        public string Injuries { get; set; }
        public string Notes { get; set; }
    }
}
